name: Generate NPM lockfile

on:
  push:
    branches: [ "main" ]
    paths:
      - "package.json"
  workflow_dispatch:

jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node (LTS)
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Create package-lock.json
        run: |
          npm install --package-lock-only
          git status

      - name: Commit lockfile (if changed)
        run: |
          if [ -n "$(git status --porcelain package-lock.json)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add package-lock.json
            git commit -m "ci: generate package-lock.json"
            git push
          else
            echo "No lockfile changes."
          fi
